---
title: "Plots"
author: "Degnan, David J"
date: "2024-4-7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "png", dpi = 300)

# Data management packages 
library(tidyverse)
library(data.table)
library(xlsx)

# Data visualization package
library(patchwork)
library(cowplot)
library(magick)
library(ggrepel)

# Statistics package
library(pROC)
```

## Figure 1

Load Data

```{r}
# Define a function to generate IDs
make_ID <- function(PMID, term1, term2) {
  paste0(c(PMID, sort(c(term1, term2))), collapse = " ")
}

# Pull algorithm performances
performance <- rbind(
  fread("./benchmark1_test.txt") %>% mutate(Dataset = "GP-GP Dataset"),
  fread("./biored_test.txt") %>% mutate(Dataset = "BioRed Dataset")
) %>%
  mutate(Dataset = factor(Dataset, levels = c("GP-GP Dataset", "BioRed Dataset")))

# Pull validation
test_validation <- fread("../data/benchmark1/degnan_test_abstracts.txt")
test_validation <- test_validation %>% 
  mutate(ID = pmap(list(PMID = PMID, term1 = Entity1, term2 = Entity2), make_ID) %>% unlist(),
         Dataset = "GP-GP Dataset")
biored_validation <- fread("../data/benchmark1/biored_test_abstracts.txt")
biored_validation <- biored_validation %>% 
  mutate(ID = pmap(list(PMID = PMID, term1 = Entity1, term2 = Entity2), make_ID) %>% unlist(),
         Dataset = "BioRed Dataset") %>%
  dplyr::select(-Sentence)
validation <- rbind(test_validation, biored_validation)
```

Make plotting dataframe

```{r}
calc_stats <- function(x) {
  x %>%
    group_by(Score, Classification) %>%
    summarise(Count = n()) %>%
    ungroup() %>%
    pivot_wider(names_from = Classification, values_from = Count, id_cols = Score) %>%
    dplyr::mutate(across(everything(), ~replace_na(.x, 0))) %>%
    mutate(
      TPR = `True Positive` / (`True Positive` + `False Negative`),
      TNR = `True Negative` / (`True Negative` + `False Positive`),
      BA = (TPR + TNR) / 2
    ) %>%
    select(Score, BA, TPR, TNR)
}

AllStats <- Reduce(function(x, y) merge(x, y, all=TRUE),
       list(calc_stats(performance %>% filter(Dataset == "GP-GP Dataset")) %>% 
              rename(`GP-GP BA` = BA, `GP-GP TPR` = TPR, `GP-GP TNR` = TNR),
            calc_stats(performance %>% filter(Dataset == "BioRed Dataset")) %>% 
              rename(`BioRed BA` = BA, `BioRed TPR` = TPR, `BioRed TNR` = TNR)), 
       accumulate=FALSE) %>%
  mutate(
    Score = ifelse(Score == "Related Term", "Relational Term", Score),
    Score = ifelse(Score == "Fixed Verb", "Fixed Term", Score)
  )
```

Make plot

```{r}
stats_res_list <- list(
  AllStats %>%
    dplyr::select(Score, `GP-GP BA`, `BioRed BA`) %>%
    pivot_longer(cols = c("GP-GP BA", "BioRed BA")) %>%
    rename(Dataset = name, BA = value) %>% 
    mutate(Dataset = gsub(" BA", "", Dataset)),
  AllStats %>%
    dplyr::select(Score, `GP-GP TPR`, `BioRed TPR`) %>%
    pivot_longer(cols = c("GP-GP TPR", "BioRed TPR")) %>%
    rename(Dataset = name, TPR = value) %>% 
    mutate(Dataset = gsub(" TPR", "", Dataset)),
  AllStats %>%
    dplyr::select(Score, `GP-GP TNR`, `BioRed TNR`) %>%
    pivot_longer(cols = c("GP-GP TNR", "BioRed TNR")) %>%
    rename(Dataset = name, TNR = value) %>% 
    mutate(Dataset = gsub(" TNR", "", Dataset)) 
)

stats_res_ex <- Reduce(function(x, y) merge(x, y, all=TRUE), stats_res_list, accumulate=FALSE) 

## Left Plot ## 
gp_res <- stats_res_ex %>%
  filter(Dataset == "GP-GP") %>%
  arrange(-BA) %>%
  mutate(Score = factor(Score, levels = unique(Score))) %>%
  pivot_longer(cols = c("BA", "TPR", "TNR")) %>%
  rename(Algorithm = Score, Score = name, Value = value) %>%
  mutate(Algorithm = factor(Algorithm, levels = rev(unique(Algorithm))))

gp_res_segment <- gp_res %>% 
  group_by(Algorithm) %>%
  summarise(Min = min(Value), Max = max(Value))

F1_Left <- ggplot() + 
  geom_segment(data = gp_res_segment, mapping = aes(x = Algorithm, 
    xend = Algorithm, y = Min, yend = Max), color = "black") + 
  geom_point(data = gp_res, mapping = aes(x = Algorithm, y = Value, 
    color = Score, shape = Score, group = Algorithm), size = 3, alpha = 0.5) + 
  theme_bw() + xlab("") + ylab("") + ggtitle("GP-GP Dataset") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), 
        legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  coord_flip()

## Right Plot ## 
br_res <- stats_res_ex %>%
  filter(Dataset == "BioRed") %>%
  arrange(-BA) %>%
  mutate(Score = factor(Score, levels = unique(Score))) %>%
  pivot_longer(cols = c("BA", "TPR", "TNR")) %>%
  rename(Algorithm = Score, Score = name, Value = value) %>%
  mutate(Algorithm = factor(Algorithm, levels = rev(unique(gp_res$Algorithm))))

br_res_segment <- br_res %>% 
  group_by(Algorithm) %>%
  summarise(Min = min(Value), Max = max(Value))

F1_Right <- ggplot() + 
  geom_segment(data = br_res_segment, mapping = aes(x = Algorithm, 
    xend = Algorithm, y = Min, yend = Max), color = "black") + 
  geom_point(data = br_res, mapping = aes(x = Algorithm, y = Value, 
    color = Score, shape = Score, group = Algorithm), size = 3, alpha = 0.5) + 
  theme_bw() + xlab("") + ylab("") + ggtitle("BioRed Dataset") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), 
        plot.title = element_text(hjust = 0.5), legend.position = "right") +
  coord_flip()

F1_Left + F1_Right
```

## Figure 2: PDF vs Clean 

```{r}
## PART A ## 
#Fig2PartA <- (ggdraw() + draw_image("../benchmarks/benchmark2/intersection_study/network_plots/PDF_Intersect_Potential_Network.png") +
#   draw_text("Possible Network", y = 0.95, size = 10) + draw_text("PDF Files", angle = 90, x = 0.05, size = 10)) + 
#(ggdraw() + draw_image("../benchmarks/benchmark2/intersection_study/network_plots/PDF_Intersect_CoOccurrence.png") + 
#   draw_text("Sentence Co-Occurrence", y = 0.95, size = 10)) + 
#(ggdraw() + draw_image("../benchmarks/benchmark2/intersection_study/network_plots/PDF_Intersect_PubMedBERT.png") + 
#   draw_text("PubMedBERT", y = 0.95, size = 10)) +
#(ggdraw() + draw_image("../benchmarks/benchmark2/intersection_study/network_plots/PDF_Intersect_SOLAR.png") +
#   draw_text("SOLAR", y = 0.95, size = 10)) + 
#(ggdraw() + draw_image("../benchmarks/benchmark2/intersection_study/network_plots/Clean_Intersect_Potential_Network.png") + 
#    draw_text("Clean Text Files", angle = 90, x = 0.05, size = 10)) + 
#(ggdraw() + draw_image("../benchmarks/benchmark2/intersection_study/network_plots/Clean_Intersect_CoOccurrence.png")) + 
#(ggdraw() + draw_image("../benchmarks/benchmark2/intersection_study/network_plots/Clean_Intersect_PubMedBERT.png")) +
#(ggdraw() + draw_image("../benchmarks/benchmark2/intersection_study/network_plots/Clean_Intersect_SOLAR.png")) +
#  plot_layout(ncol = 4)
#ggsave(filename = "Fig2PartA.png", plot = Fig2PartA, dpi = 300, width = 2400, height = 1200, units = "px")

Fig2PartA <- ggdraw() + draw_image("Fig2PartA.png")

fig2_stats <- fread("./B2_Intesection_Study_Metrics.csv") %>%
  rename(TPR = TPR.True.Positive, TNR = TNR.True.Negative) %>%
  mutate(BA = (TPR + TNR) / 2) %>%
  select(Dataset, Algorithm, TPR, TNR, BA)

## PDF Plot ## 
pdf_fig2_stats <- fig2_stats %>% 
  filter(Dataset == "PDF") %>%
  pivot_longer(cols = c("BA", "TPR", "TNR")) %>%
  mutate(Algorithm = factor(Algorithm, levels = c("SOLAR", "PubMedBERT", "Co-Occurrence"))) %>%
  rename(Score = name, Value = value)

pdf_fig2_segment <- pdf_fig2_stats %>% 
  group_by(Algorithm) %>%
  summarise(Min = min(Value), Max = max(Value))

Fig2PartB <- ggplot() + 
  geom_segment(data = pdf_fig2_segment, mapping = aes(x = Algorithm, 
    xend = Algorithm, y = Min, yend = Max), color = "black") + 
  geom_point(data = pdf_fig2_stats, mapping = aes(x = Algorithm, y = Value, 
    color = Score, shape = Score, group = Algorithm), size = 3, alpha = 0.5) + 
  theme_bw() + xlab("") + ylab("") + ggtitle("PDF") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), 
        legend.position = "none",
        plot.title = element_text(hjust = 0.5)) +
  coord_flip()

## Clean Plot ## 
clean_fig2_stats <- fig2_stats %>% 
  filter(Dataset == "Clean") %>%
  pivot_longer(cols = c("BA", "TPR", "TNR")) %>%
  mutate(Algorithm = factor(Algorithm, levels = c("SOLAR", "PubMedBERT", "Co-Occurrence"))) %>%
  rename(Score = name, Value = value)

clean_fig2_segment <- clean_fig2_stats %>% 
  group_by(Algorithm) %>%
  summarise(Min = min(Value), Max = max(Value))

Fig2PartC <- ggplot() + 
  geom_segment(data = clean_fig2_segment, mapping = aes(x = Algorithm, 
    xend = Algorithm, y = Min, yend = Max), color = "black") + 
  geom_point(data = clean_fig2_stats, mapping = aes(x = Algorithm, y = Value, 
    color = Score, shape = Score, group = Algorithm), size = 3, alpha = 0.5) + 
  theme_bw() + xlab("") + ylab("") + ggtitle("Clean") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), 
        legend.position = "right",
        plot.title = element_text(hjust = 0.5)) +
  coord_flip()

Fig2PartA / (Fig2PartB + Fig2PartC) + plot_layout(height = c(5, 1)) + plot_annotation(tag_levels = "A")
```

```{r}
b2_metrics <- read.xlsx("B2_Network_Metrics.xlsx", 1)

bar_chart_plot <- function(Algorithm, Type, Metric, metric_name, target_value) {
  data.frame(Algorithm = Algorithm, Type = Type, Metric = Metric) %>%
    arrange(-Metric) %>%
    mutate(Algorithm = factor(Algorithm, levels = Algorithm)) %>%
    ggplot(aes(x = Algorithm, y = Metric, fill = Type)) +
      geom_bar(stat = "identity", color = "black") +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +
      geom_hline(yintercept = target_value, color = "firebrick4") +
      xlab("") +
      ylab(metric_name)
}

FigB_A <- bar_chart_plot(b2_metrics$Algorithm[2:12], b2_metrics$Type[2:12], b2_metrics$Num_Correct_Edges[2:12], 
              "Number Correct Edges", b2_metrics$Num_Correct_Edges[1]) + theme(legend.position = "none")
FigB_B <- bar_chart_plot(b2_metrics$Algorithm[2:12], b2_metrics$Type[2:12], b2_metrics$Num_Incorrect_Edges[2:12], 
              "Number Incorrect Edges", b2_metrics$Num_Incorrect_Edges[1]) + theme(legend.position = "none")
FigB_C <- bar_chart_plot(b2_metrics$Algorithm[2:12], b2_metrics$Type[2:12], b2_metrics$Connectedness[2:12], 
              "Connectedness", b2_metrics$Connectedness[1]) + theme(legend.position = "none")
FigB_D <- bar_chart_plot(b2_metrics$Algorithm[2:12], b2_metrics$Type[2:12], b2_metrics$Clustering_Coefficient[2:12], 
              "Clustering Coefficient", b2_metrics$Clustering_Coefficient[1]) + theme(legend.position = "none")
FigB_E <- bar_chart_plot(b2_metrics$Algorithm[2:12], b2_metrics$Type[2:12], b2_metrics$Num_Components[2:12], 
              "Number Components", b2_metrics$Num_Components[1]) + theme(legend.position = "none")
FigB_F <- bar_chart_plot(b2_metrics$Algorithm[2:12], b2_metrics$Type[2:12], b2_metrics$Average_Component_Size[2:12], 
              "Average Component Size", b2_metrics$Average_Component_Size[1]) + theme(legend.position = "none")
FigB_G <- bar_chart_plot(b2_metrics$Algorithm[2:12], b2_metrics$Type[2:12], b2_metrics$Average_Neighborhood_Size[2:12], 
              "Average Neighborhood Size", b2_metrics$Average_Neighborhood_Size[1]) + theme(legend.position = "none")
FigB_pre <- bar_chart_plot(b2_metrics$Algorithm[2:12], b2_metrics$Type[2:12], b2_metrics$GED[2:12], 
              "Graph Edit Distance", b2_metrics$GED[1]) 
FigB_H <- FigB_pre + theme(legend.position = "none")
FigB_I <- cowplot::get_legend(FigB_pre)

FigB_A + FigB_B + FigB_C + FigB_D + FigB_E + FigB_F + FigB_G + FigB_H + FigB_I

```




## Figure 3: Benchmark 2 

```{r}
## PART A ## 
#Fig3PartA <- (ggdraw() + draw_image("../benchmarks/benchmark2/results/networks/Truth.png") +
#   draw_text("Possible Network", y = 0.95, size = 10)) + 
#(ggdraw() + draw_image("../benchmarks/benchmark2/results/networks/CoOccurrence.png") + 
#   draw_text("Sentence Co-Occurrence", y = 0.95, size = 10)) + 
#(ggdraw() + draw_image("../benchmarks/benchmark2/results/networks/RelTerm.png") + 
#   draw_text("Related Term", y = 0.95, size = 10)) +
#(ggdraw() + draw_image("../benchmarks/benchmark2/results/networks/FixedVerb.png") +
#   draw_text("Fixed Verb", y = 0.95, size = 10)) + 
#(ggdraw() + draw_image("../benchmarks/benchmark2/results/networks/pubmedmineR05.png") +
#   draw_text("pubmed.mineR + Cosine 0.5", y = 0.95, size = 10)) + 
#(ggdraw() + draw_image("../benchmarks/benchmark2/results/networks/Reach.png") +
#   draw_text("REACH", y = 0.95, size = 10)) + 
#(ggdraw() + draw_image("../benchmarks/benchmark2/results/networks/PubMedBERT.png") +
#   draw_text("PubMedBERT", y = 0.95, size = 10)) +
#(ggdraw() + draw_image("../benchmarks/benchmark2/results/networks/BioBERT.png") +
#   draw_text("BioBERT", y = 0.95, size = 10)) +
#(ggdraw() + draw_image("../benchmarks/benchmark2/results/networks/BioGPT.png") +
#   draw_text("BioGPT", y = 0.95, size = 10)) +
#  plot_layout(ncol = 5)
#ggsave(filename = "Fig3PartA.png", plot = Fig3PartA, dpi = 300, width = 2400, height = 1200, units = "px")

Fig3PartA <- ggdraw() + draw_image("Fig3PartA.png")

## PART B ##
Fig3PartB <- fread("~/Git_Repos/nlp_benchmark/plots/B2_Metrics.csv") %>%
  ggplot(aes(x = FPR.False.Positive, y = TPR.True.Positive, label = Algorithm)) + geom_point() + geom_text_repel() + theme_bw() +
  xlab("False Positive Rate") + ylab("True Positive Rate") 

Fig3PartA / Fig3PartB + plot_layout(height = c(2, 1)) + plot_annotation(tag_levels = "A")
```

## Supplemental Figure 1

Here, we see the cosine correlation ROC curve for separating relationship and 
not relationship cases.

```{r}
# Read data and make roc curve
pmed_train <- fread("~/Git_Repos/nlp_benchmark/plots/training_pubmedmineR_and_cosine.txt")
pmed_train_roc <- pROC::roc(Annotation ~ Score, data = pmed_train)
roc_curve_plot <- ggroc(pmed_train_roc, legacy.axes = TRUE) + xlab("FPR") + ylab("TPR") +
  geom_abline(intercept = 0, slope = 1,
                color = "darkgrey", linetype = "dashed") +
  ggtitle("AUC = 0.6293") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

# Calculate 1:1 cost - the penalty for false positives and false negatives is the same
# P is proportion of true positives in training set
C_1 <- function(x, y, p = 486/819) {(1-p)*1*x + p*1*(1-y)}

cost_df <- data.frame(
  Score = pmed_train_roc$thresholds,
  Specificity = pmed_train_roc$specificities,
  Sensitivity = pmed_train_roc$sensitivities
) %>%
  filter(!is.infinite(Score)) %>%
  mutate(Cost = purrr::map2(Specificity, Sensitivity, C_1) %>% unlist())

cost_plot <- ggplot(cost_df, aes(x = Score, y = Cost)) +
  geom_line() +
  theme_bw() +
  xlab("Cosine Correlation Score") +
  ylab("1:1 Cost") + 
  ggtitle("Optimum Score: 0.03")

FigS1 <- roc_curve_plot + cost_plot + plot_annotation(tag_levels = "A")
FigS1
```

